### ISSUE TITLE
OSError: cannot open recource

### ISSUE THREAD

**Issue by ryzetech** [fergofrog/microwave_usb_fan#1]
I opened the example and tried it out. First, I hat do install Pillow, then I got this:
```
Traceback (most recent call last):
  File "C:\Users\...\usbfan_test.py", line 3, in <module>
    p = Program((TextMessage("Test1"),
  File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\usbfan\message.py", line 12, in __init__
    join(basename(__file__), 'fonts', 'Arial.ttf'))
  File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\ImageFont.py", line 280, in truetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\ImageFont.py", line 145, in __init__
    layout_engine=layout_engine)
OSError: cannot open resource
```
I tried to change the font to Arial (as it's saying above). Welp, what to do?
Btw using Py 3.7.2

**Comment by fergofrog** [comment]
The code on line 12 of message.py (`join(basename(__file__), 'fonts', 'Hack-Regular.ttf')`) is creating the path to the file Hack-Regular.ttf from the fonts directory. If you want to use another font, you'll need to place a TrueType or OpenType font file alongside Hack-Regular.ttf in the fonts directory and change the path (as you've already done).

**Comment by rjmatthews62** [comment]
Yes, I also see the font bug. Also, the pip install does not include the fonts folder.
Once those are fixed, this worked fine, so thanks very much!

**Comment by fergofrog** [comment]
Cheers @rjmatthews62! I had checked the source distribution included the fonts, but not that they were installed with the package.

**Comment by rjmatthews62** [comment]
Ta.
So, in my version of the fan editor, you can set different modes for each message: a start, a middle, and an end sequence. Did you spot how those were encoded in your testing?

**Comment by rjmatthews62** [comment]
Also, ps: Shouldn't it be dirname, not basename?

**Comment by fergofrog** [comment]
Hmm, yes, why was that working for me in the first place :/
